### ISSUE TITLE
Do you have a backup of the data set？

### ISSUE THREAD

**Issue by xdmdtz123** [PACE-challenge/Treewidth#1]

**Comment by holgerdell** [comment]
Thanks for noticing the broken link! I think I found the files you were looking for and I added the archive as a [github release](https://github.com/PACE-challenge/Treewidth/releases/download/SAT-competition-gaifman/SAT-competition-gaifman.zip) in this repository. I also updated the link.

Note that you can compute these graphs yourself from the SAT benchmark instances by computing the Gaifman graph of the CNF formulas (variables become nodes; if two variables are in the same clause (regardless of negations), then the corresponding nodes will be adjacent).
